[build]
  base = "client"
  publish = "dist"
  command = "pnpm run build"

[build.environment]
  PNPM_VERSION = "8"
  NODE_VERSION = "18"

# Single Page Application redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm dev"
  port = 5174
  publish = "dist"
